server:
  port: 6868

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventsphere?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: duytu
    password: 17082004Tu.
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update  # Keep schema between restarts
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: duytu178204@gmail.com
    password: piyrylztmzmxijww
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: "MySuperSecretKeyForEventSphereApplicationThatIsLongEnoughForHS512AlgorithmAndSecureEnoughForProductionUse123456789"
  expiration: 86400   # seconds (1 day)
admin:
  email: 
  password: 
  name: 
logging:
  level:
    org.springframework.security: DEBUG
