-- Create event_edit_requests table
CREATE TABLE event_edit_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,
    requested_data JSONB NOT NULL,
    original_data JSONB NOT NULL,
    admin_id BIGINT,
    admin_notes TEXT,
    processed_at TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (event_id) REFERENCES events(event_id),
    FOREIGN KEY (requester_id) REFERENCES users(user_id),
    FOREIGN KEY (admin_id) REFERENCES users(user_id)
);

-- Create admin_notifications table
CREATE TABLE admin_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    related_entity_id BIGINT,
    related_entity_type VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE
);

-- Create indexes for better performance
CREATE INDEX idx_event_edit_requests_event_id ON event_edit_requests(event_id);
CREATE INDEX idx_event_edit_requests_requester_id ON event_edit_requests(requester_id);
CREATE INDEX idx_event_edit_requests_status ON event_edit_requests(status);
CREATE INDEX idx_admin_notifications_type ON admin_notifications(type);
CREATE INDEX idx_admin_notifications_is_read ON admin_notifications(is_read);

