server:
  port: 6868

spring:
  datasource:
     url: jdbc:mysql://localhost:3306/eventsphere?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
     username: appuser
     password: "17082004Tu!"
     driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # dev: update, prod: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: "change_this_secret_key_to_strong_random_value"
  expiration: 86400   # seconds (1 day)
admin:
  email: ${ADMIN_EMAIL:admin@eventsphere.local}
  password: ${ADMIN_PASSWORD:Admin@123}
  name: ${ADMIN_NAME:System Administrator}
logging:
  level:
    org.springframework.security: DEBUG
