spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventsphere?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: \
    password: \
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 6868

jwt:
  secret: \
  expiration: 86400
