server:
  port: 6868

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventsphere?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: duytu
    password: 17082004Tu.
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: none         # Disable JPA auto DDL
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

  flyway:
    enabled: false
    locations: classpath:db/migration

jwt:
  secret: "change_this_secret_key_to_strong_random_value"
  expiration: 86400   # seconds (1 day)
admin:
  email: ${ADMIN_EMAIL:admin@eventsphere.local}
  password: ${ADMIN_PASSWORD:Admin@123}
  name: ${ADMIN_NAME:System Administrator}
logging:
  level:
    org.springframework.security: DEBUG
